config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'loop' => 'loop#index'
  get 'multi_loop' => 'multi_loop#index'

end

app/models/loop.rb
class Loop
  include ActiveModel::Model

  attr_reader :loop_name, :hashes

  def initialize(number_of_hashes = 3, loop_name = "Tes t1")
    @loop_name = loop_name
    @hashes = create_random_hashes(number_of_hashes)
  end

  def create_random_hashes(number_of_hashes)
    Array.new(number_of_hashes) { create_random_hash }
  end

  def create_random_hash
    Digest::MD5.hexdigest(Random.rand(100).to_s)
  end
end

app/models/multi_loop.rb
class MultiLoop
  attr_reader :hash, :inner_hashes, :loop_name

  def initialize(number_of_hashes, loop_name, number_of_inner_loops, name_of_inner_loop)
    @loop_name = loop_name
    @hash = create_random_hashes(number_of_hashes.to_i)
    @inner_hashes = {}
    prepare_inner_loop(number_of_inner_loops.to_i, name_of_inner_loop)
  end

  def prepare_inner_loop(number_of_inner_loops, name_of_inner_loop)
    @hash.each do | hash |
      @inner_hashes[hash.to_sym] = Loop.new(number_of_inner_loops, name_of_inner_loop)
    end
  end

  def create_random_hashes(number_of_hashes)
    Array.new(number_of_hashes) { create_random_hash }
  end

  def create_random_hash
    Digest::MD5.hexdigest(Random.rand(100).to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/loop_controller.rb
class LoopController < ApplicationController
  def index
    @loop = Loop.new(params[:number_of_loops].to_i)
    @name = params[:test_run_name]
    @hashes = @loop.hashes
    @loops_for_select = ApplicationHelper.get_loops_for_run
  end
end

app/controllers/multi_loop_controller.rb
class MultiLoopController < ApplicationController
  def index
    @name = params[:test_run_name]
    @multi_loop =
        MultiLoop.new(
          params[:outer_loops],
          params[:outer_loop_name],
          params[:inner_loops],
          params[:inner_loop_name]
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @loops_for_select = ApplicationHelper.get_loops_for_run
    @inner_loops = ApplicationHelper.get_inner_loop
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.maximum_of_loops
    10
  end

  def self.maximum_inner_loop
    3
  end

  def self.get_inner_loop
    [*1..maximum_inner_loop]
  end

  def self.get_loops_for_run
    [*1..maximum_of_loops]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/loop/index.html.erb
<h1>Loop Hash Runner</h1>
<div class="row">
  <div class="col-md-offset-1">
    <h2>Test run name: <%= @name %></h2>
  </div>
</div>
<div class="col-md-offset-2">
  <% @hashes.each_with_index do |hashes, index| %>
    <p>Round and round goes the loop. Iteration no. <%= index + 1 %>.</p>
    <p> <%= hashes %> </p>
  <% end %>
</div>
<%= render 'shared/loop_form' %>

app/views/multi_loop/index.html.erb
<h1>Loop Hash Runner</h1>
<div class="row">
  <div class="col-md-offset-1">
    <h2>Test run name: <%= @name %></h2>
  </div>
</div>
<div class="col-md-offset-1">
  <% @multi_loop.hash.each_with_index do | hash, index | %>
    <p>Loop name: <%= @multi_loop.loop_name %> </p>
    <p>Round and round goes the loop. Iteration no.  <%= index + 1 %></p>
    <p> <%= hash %> </p>
      <p>Inner loop name: <%= @multi_loop.inner_hashes[hash.to_sym].loop_name %></p>
      <% @multi_loop.inner_hashes[hash.to_sym].hashes.each_with_index do | inner_hash, index | %>
        <p>Random text number <%= index + 1 %> from this scope: <%= inner_hash %></p>
      <% end %>
      <p>Random text from scope above: <%= hash %>
  <% end %>
</div>

app/views/shared/_loop_form.html.erb
<%= form_tag(loop_path, method: 'get') do %>
    <div class="row">
      <%= label_tag(:test_run_name, 'Name for Test Run') %>
      <%= text_field_tag(:test_run_name) %>
    </div>
    <div class="row">
      <%= label_tag(:number_of_loops, 'Number of loops') %>
      <%= select_tag(:number_of_loops, options_for_select(@loops_for_select)) %>
    </div>
    <div class="row">
      <%= submit_tag('Get Loops', class: 'btn btn-success') %>
    </div>

<% end %>

app/views/shared/_multi_loop_form.html.erb
<%= form_tag(multi_loop_path, method: 'get') do %>
    <div class="row">
      <%= label_tag(:test_run_name, 'Name for Test Run') %>
      <%= text_field_tag(:test_run_name) %>
    </div>
    <div class="row">
      <%= label_tag(:outer_loops, 'Number of outer loops') %>
      <%= select_tag(:outer_loops, options_for_select(@loops_for_select)) %>
    </div>
    <div class="row">
      <%= label_tag(:outer_loop_name, 'Name for outer loop') %>
      <%= text_field_tag(:outer_loop_name) %>
    </div>
    <div class="row">
      <%= label_tag(:inner_loops, 'Number for inner loops') %>
      <%= select_tag(:inner_loops, options_for_select(@inner_loops)) %>
    </div>
    <div class="row">
      <%= label_tag(:inner_loop_name, 'Name for inner_loop') %>
      <%= text_field_tag(:inner_loop_name) %>
    </div>
    <div class="row">
      <%= submit_tag('Get Loops', class: 'btn btn-success') %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Welcome to the eWings Test Application</h1>
</div>
<div class="row">
  <div class="col-md-3 col-md-offset-2">
    <%= render 'shared/loop_form' %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= render 'shared/multi_loop_form' %>
  </div>
</div>